version: '3'

services:
  api:
    build: .
    image: financex-server
    container_name: financex-server
    command: yarn run start:prod
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - POSTGRES_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@financex-postgres:5432/${POSTGRES_DB}
      - MONGODB_DATABASE_URL=mongodb://${MONGODB_ROOT_USER}:${MONGODB_ROOT_PASSWORD}@financex-mongodb:27017
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME}
      - REDIS_HOST=financex-cache
      - REDIS_PORT=6379
      - PORT=${SERVER_PORT}
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - financex-network

  redis:
    image: redis:latest
    container_name: financex-cache
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    command: redis-server --port 6379
    networks:
      - financex-network

  postgres:
    image: postgres:latest
    container_name: financex-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - financex-network

  mongodb:
    image: mongo:latest
    container_name: financex-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    networks:
      - financex-network

volumes:
  cache:
    driver: local
  pgdata:
    driver: local

networks:
  financex-network:
    driver: bridge
